[project]
name = 'Notification-Anxiety-Orchestration-System'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.deep-work-disruption-engine]
path = 'contracts/deep-work-disruption-engine.clar'
clarity_version = 3
epoch = '3.2'

[contracts.weekend-email-urgency-fabricator]
path = 'contracts/weekend-email-urgency-fabricator.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
